font_family Maple Mono NL NF CN Medium

hide_window_decorations yes

background_opacity 0.8
background_blur 1

startup_session startup.session

map ctrl+c copy_or_interrupt
map ctrl+v paste_from_clipboard
map ctrl+shift+c send_key ctrl+c
map ctrl+shift+v send_key ctrl+v

include themes/noctalia.conf
